# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml


# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: cellphonedb_max

# Metadata for your component
info:
  # A relatively short label, used when rendering visualisations (required)
  label: Cellphonedb Max
  # A one sentence summary of how this method works (required). Used when 
  # rendering summary tables.
  summary: "Inferring cell_cell communication from combined expression of multi-subunit ligand_receptor complexes"
  # A multi-line description of how this component works (required). Used
  # when rendering reference documentation.
  description: |
    FILL IN: A (multi-line) description of how this method works.
  # Which normalisation method this component prefers to use (required).
  preferred_normalization: log_cp10k
  # A reference key from the bibtex library at src/common/library.bib (required).
  reference: efremova2020cellphonedb
  # URL to the documentation for this method (required).
  documentation_url: https://www.cellphonedb.org/index.html
  # URL to the code repository for this method (required).
  repository_url: https://github.com/Teichlab/cellphonedb

# Component-specific parameters (optional)
arguments:
  # - name: "--n_neighbors"
  #   type: "integer"
  #   default: 5
  #   description: Number of neighbors to use.
  - name: "--test"
    type: boolean
    default: false
    description: Whether to test or not.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: python_script
    path: script.py
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: python
        packages: 
          - liana
          - pandas

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
